/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import static domain.Admin.*;
import java.awt.*;
import java.awt.Image;
import java.io.*;

import javax.swing.*;

/**
 *
 * @author mateo
 */
public class ManangerUi extends javax.swing.JFrame {

    int width = 800;
    int height = 600;
    private ImageIcon imagen;
    private Icon icono;
    File folder = new File("C:\\Users\\mateo\\Downloads");
    /**
     * Creates new form ManangerUi
     */
    public ManangerUi() {
        initComponents();
        setTitle("Files Mananger");
        setSize(width, height);
        setLocationRelativeTo(null);
        this.pintarImagen(labelIcon, "C:\\Cursos\\Java\\FundamentosNuevoNivel\\ManangerDownloaded\\src\\com\\imagenes\\icon.png");
        this.pintarImagen(labelFolder, "C:\\Cursos\\Java\\FundamentosNuevoNivel\\ManangerDownloaded\\src\\com\\imagenes\\folder.png");
        btnShowUrlPDFs.setVisible(false);
        btnShowUrlImg.setVisible(false);
        btnShowUrlDirectory.setVisible(false);
        btnShowUrlZips.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainScreenPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbltxtVertical = new javax.swing.JLabel();
        labelFolder = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDirectoryFolders = new javax.swing.JButton();
        btnShowUrlDirectory = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnImageFolder = new javax.swing.JButton();
        btnShowUrlImg = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPDFsFolder = new javax.swing.JButton();
        btnShowUrlPDFs = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnZipFolders = new javax.swing.JButton();
        btnShowUrlZips = new javax.swing.JButton();
        panelViewResults = new javax.swing.JPanel();
        lblResults = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainScreenPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainScreenPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltxtVertical.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        lbltxtVertical.setForeground(new java.awt.Color(0, 0, 0));
        lbltxtVertical.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltxtVertical.setText("manage files");
        lbltxtVertical.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lbltxtVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 260));
        jPanel1.add(labelFolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, 160));

        MainScreenPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 440));

        labelIcon.setBackground(new java.awt.Color(102, 255, 255));
        labelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainScreenPanel.add(labelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 160));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lobster", 3, 24)); // NOI18N
        jLabel1.setText("Limpiar Carpeta De Descargas De Directorios Nuevos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 560, 80));

        btnDirectoryFolders.setBackground(new java.awt.Color(0, 255, 255));
        btnDirectoryFolders.setText("Click Aqui");
        btnDirectoryFolders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectoryFoldersActionPerformed(evt);
            }
        });
        jPanel2.add(btnDirectoryFolders, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 90, 30));

        btnShowUrlDirectory.setBackground(new java.awt.Color(0, 255, 255));
        btnShowUrlDirectory.setFont(new java.awt.Font("Malgun Gothic", 3, 12)); // NOI18N
        btnShowUrlDirectory.setText("Mostrar Directorio");
        btnShowUrlDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowUrlDirectoryActionPerformed(evt);
            }
        });
        jPanel2.add(btnShowUrlDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        MainScreenPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 560, 110));

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lobster", 3, 24)); // NOI18N
        jLabel2.setText("Limpiar Carpeta De Descargas De Imagenes");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 560, 80));

        btnImageFolder.setBackground(new java.awt.Color(0, 255, 255));
        btnImageFolder.setText("Click Aqui");
        btnImageFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageFolderActionPerformed(evt);
            }
        });
        jPanel3.add(btnImageFolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 90, 30));

        btnShowUrlImg.setBackground(new java.awt.Color(0, 255, 255));
        btnShowUrlImg.setFont(new java.awt.Font("Malgun Gothic", 3, 12)); // NOI18N
        btnShowUrlImg.setText("Mostrar Directorio");
        btnShowUrlImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowUrlImgActionPerformed(evt);
            }
        });
        jPanel3.add(btnShowUrlImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        MainScreenPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 560, 110));

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lobster", 3, 24)); // NOI18N
        jLabel3.setText("Limpiar Carpeta De Descargas De Archivos PDFs");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 560, 80));

        btnPDFsFolder.setBackground(new java.awt.Color(0, 255, 255));
        btnPDFsFolder.setText("Click Aqui");
        btnPDFsFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFsFolderActionPerformed(evt);
            }
        });
        jPanel4.add(btnPDFsFolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 90, 30));

        btnShowUrlPDFs.setBackground(new java.awt.Color(0, 255, 255));
        btnShowUrlPDFs.setFont(new java.awt.Font("Malgun Gothic", 3, 12)); // NOI18N
        btnShowUrlPDFs.setText("Mostrar Directorio");
        btnShowUrlPDFs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowUrlPDFsActionPerformed(evt);
            }
        });
        jPanel4.add(btnShowUrlPDFs, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        MainScreenPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 560, 110));

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lobster", 3, 24)); // NOI18N
        jLabel4.setText("Limpiar Carpeta De Descargas De Archivos Zip");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 560, 80));

        btnZipFolders.setBackground(new java.awt.Color(0, 255, 255));
        btnZipFolders.setText("Click Aqui");
        btnZipFolders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZipFoldersActionPerformed(evt);
            }
        });
        jPanel5.add(btnZipFolders, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 90, 30));

        btnShowUrlZips.setBackground(new java.awt.Color(0, 255, 255));
        btnShowUrlZips.setFont(new java.awt.Font("Malgun Gothic", 3, 12)); // NOI18N
        btnShowUrlZips.setText("Mostrar Directorio");
        btnShowUrlZips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowUrlZipsActionPerformed(evt);
            }
        });
        jPanel5.add(btnShowUrlZips, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        MainScreenPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 560, 110));

        panelViewResults.setBackground(new java.awt.Color(255, 255, 255));
        panelViewResults.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResults.setFont(new java.awt.Font("Lobster", 3, 24)); // NOI18N
        panelViewResults.add(lblResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 60));

        MainScreenPanel.add(panelViewResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 560, 100));

        getContentPane().add(MainScreenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImageFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageFolderActionPerformed
        // TODO add your handling code here:
        //Llamamos al Metodo Que busca las imagenes en la carpeta de descargas
        try {
            findAllFilesImagenesInFolder(folder);
            lblResults.setText("Se Realizo Con exito la transferencia");
            btnShowUrlImg.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sucedio un error" + ex.getMessage());
        }
    }//GEN-LAST:event_btnImageFolderActionPerformed

    private void btnPDFsFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFsFolderActionPerformed
        // TODO add your handling code here:
        try {
            findAllPdfFiles(folder);
            lblResults.setText("Se Realizo Con exito la transferencia");
            btnShowUrlPDFs.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sucedio un error" + ex.getMessage());
        }
    }//GEN-LAST:event_btnPDFsFolderActionPerformed

    private void btnZipFoldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZipFoldersActionPerformed
        // TODO add your handling code here:
        try {
            findAllZipFiles(folder);
            lblResults.setText("Se Realizo Con exito la transferencia");
            btnShowUrlZips.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sucedio un error" + ex.getMessage());
        }
    }//GEN-LAST:event_btnZipFoldersActionPerformed

    private void btnDirectoryFoldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectoryFoldersActionPerformed
        // TODO add your handling code here:
        try {
            findAllFolderFiles(folder);
            lblResults.setText("Se Realizo Con exito la transferencia");
            btnShowUrlDirectory.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sucedio un error" + ex.getMessage());
        }
    }//GEN-LAST:event_btnDirectoryFoldersActionPerformed

    private void btnShowUrlDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowUrlDirectoryActionPerformed
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("C:\\Windows\\System32\\cmd.exe /K start C:\\Users\\mateo\\OneDrive\\Documentos\\CarpetasDownloaded");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnShowUrlDirectoryActionPerformed

    private void btnShowUrlImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowUrlImgActionPerformed
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("C:\\Windows\\System32\\cmd.exe /K start C:\\Users\\mateo\\OneDrive\\Imágenes\\ImagenesDescargadas");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnShowUrlImgActionPerformed

    private void btnShowUrlPDFsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowUrlPDFsActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("C:\\Windows\\System32\\cmd.exe /K start C:\\Users\\mateo\\OneDrive\\Documentos\\PdfDownloaded");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnShowUrlPDFsActionPerformed

    private void btnShowUrlZipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowUrlZipsActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("C:\\Windows\\System32\\cmd.exe /K start C:\\Users\\mateo\\OneDrive\\Documentos\\CarpetasZip");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnShowUrlZipsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManangerUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManangerUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManangerUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManangerUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManangerUi().setVisible(true);
            }
        });
    }

    private void pintarImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainScreenPanel;
    private javax.swing.JButton btnDirectoryFolders;
    private javax.swing.JButton btnImageFolder;
    private javax.swing.JButton btnPDFsFolder;
    private javax.swing.JButton btnShowUrlDirectory;
    private javax.swing.JButton btnShowUrlImg;
    private javax.swing.JButton btnShowUrlPDFs;
    private javax.swing.JButton btnShowUrlZips;
    private javax.swing.JButton btnZipFolders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelFolder;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lbltxtVertical;
    private javax.swing.JPanel panelViewResults;
    // End of variables declaration//GEN-END:variables
}
